### ISSUE TITLE
Wow really?

### ISSUE THREAD

**Issue by quantizor** [krainboltgreene/hexpress#1]
Way to rip off VerbalExpressions... syntax and all.

https://github.com/VerbalExpressions/JSVerbalExpressions?source=c

**Comment by jacquescrocker** [comment]
hexpress has a great api, is well tested, and looks like a really useful library. why the hate?

**Comment by quantizor** [comment]
Look at both projects and tell me one doesn't look like a blatant rip of the other.

**Comment by davidcelis** [comment]
Very constructive, @Evster88. :ok_hand:

But really. Take your own advice and look at both projects. Look at the code behind [the Ruby port of VerbalExpressions](https://github.com/ryan-endacott/verbal_expressions) and this library and tell us they're the same. Hell, even read more than half of this project's README to see the extremely obvious differences. Who cares if the syntax is so similar? It's a good DSL. Just be happy that there's another good (and more powerful) option out there.

**Comment by krainboltgreene** [comment]
@Evster88: What's the difference between a "rip off" and a new implementation of the spec? I'll tell you: The latter usually attempts to implement the spec!

You may want to check out `lib/hexpress/verbal_expressions.rb` and `spec/lib/verbal_expressions_standard.rb`

You can also read the README where I point out this is a reimagining of Verbal Expressions.

**Comment by krainboltgreene** [comment]
Re-opening this because I think it's going to pop up later as well and adding that VerbalExpressions isn't even the first attempt at this: http://rubydoc.info/gems/TextualRegexp/1.8.6/frames (Note the 2007 copyright).
