### ISSUE TITLE
#to_r easily confused with Numeric#to_r :(

### ISSUE THREAD

**Issue by yaauie** [krainboltgreene/hexpress#8]
`#to_r` means 'to rational' everywhere else. Perhaps supply a more descriptive method for clarity?

**Comment by krainboltgreene** [comment]
Good point, ruby tries to look for .to_regexp: http://www.ruby-doc.org/core-2.0.0/Regexp.html#method-c-try_convert

I'll have to push a new major version to fix this, but I was going to anyways.

**Comment by yaauie** [comment]
Oops. Looks like this is a dup of #2.
